# Info:
# https://docs.travis-ci.com/user/languages/r/
# https://docs.travis-ci.com/user/database-setup/#MySQL

language: r
sudo: required
warnings_are_errors: true

services:
  - mysql

#r_check_revdep: true

apt_packages:
 - libmysqlclient-dev

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'travis'@'localhost'; FLUSH PRIVILEGES;" -uroot
